### ISSUE TITLE
App Logs are growing big too fast

### ISSUE THREAD

**Issue by lilszi** [KomodoPlatform/atomicDEX-Pro#231] opened 2020-06-09 06:08 UTC
I have 300+ MB of App logs in 24 hours, therefore, I am proposing the following solutions:

1. Have an option to turn logs on/off
2. Reduce log file size by changing the level of verbosity of the log.
3. Manual Price API & Transactions refresh instead of continuous background refresh (or maybe this could be excluded in the lowest verbose level) because this is what takes out most of the log content. 

In any case, the mm2 DB is there to debug any swap related issues, and the logging/verbosity could be turned back on/up if there is an issue requires debugging in the app.

**Comment by tonymorony** [comment] 2020-06-09 17:56
@lilszi thanks for issue opening!

are you on Windows?
If thats the case - 2 caused by 
https://github.com/KomodoPlatform/atomicDEX-Pro/issues/227 
As soon as log rotation will be fixed on Windows it'll be same as on other platforms (up to two files 7.77 Mb each).

I don't think that 1. is a good option because it'll be not possible to collect problem about issue. It's alpha testing and logs is one of the main things we need.

3. - probably @Milerius can advice on that. At the moment this information auto-refresting every 30 seconds. Is it causing some problems on your side (besides of logs growing problem)?

**Comment by lilszi** [comment] 2020-06-09 18:02
Yes, Windows 10 latest build. - If #227 will fix these then fine. 

3 - just mentioned because most of the log contents are these API calls

I am not sure if any of these are causing my problems, today my whole history went awol, and new swaps are disappearing from the list. but that will be another issue. Informed @SirSevenG in DM we'll see if it's an issue worthy.

**Comment by cipig** [comment] 2020-06-09 18:50
orderbook is called every 5s when in DEX tab and the rpc response is logged
maybe remove response from log, just like for my_recent_swaps and tx_history... should make log much smaller

**Comment by Milerius** [comment] 2020-06-11 04:59
Normally #232 should solve all of our problem currently, i don't like RPC answer anymore, but rpc answer code, if the answer code is not 200, it's will print the error body, I think it's will be more usefull from a QA perspective, and fetching informations from coinpaprika is now every 2minute ty @cipig for the suggestion.

**Comment by tonymorony** [comment] 2020-06-12 00:05
New logging system seems to be really cool, and in 0.2.15 this problem will be resolved (already possible to test on CI artifacts, from this run lets say https://github.com/KomodoPlatform/atomicDEX-Pro/actions/runs/130816072 ) 

Closing this one. Feel free to open new issue in case of suggestions on new log content / info needs to be added

**Closed by tonymorony** 2020-06-12 00:05 UTC
