### ISSUE TITLE
Crahes on 0.1.4

### ISSUE THREAD

**Issue by SirSevenG** [KomodoPlatform/atomicDEX-Pro#222] opened 2020-06-06 17:21 UTC
Reported by users
allbits:
https://discordapp.com/channels/412898016371015680/705374203972419616/718858385134452790
Oszy, in DM

Ubuntu:
In logs app crashes silently, after getting bad responses (not 200 // resp: Couldn't connect to server), example: https://paste.ubuntu.com/p/DCqTsJSSxF/

Win:
Crashes right after `[rotate log threa] rotate_log`, not much info logs.

Can't reproduce either at 1st try.
To investigate:
1. Ubuntu: `19.10`, `5.3.0-18-generic`
Need to check on not updated eoan release.
2. Win 1909
Spam orders, wait till log rotates.

**Comment by tonymorony** [comment] 2020-06-06 21:42
I've reproduced issue on Windows - that looks like logs rotating problem, yeah (app stops each time when log exceed rotation size (7.77 MB) )
We'll debug tomorrow with @Milerius

**Comment by tonymorony** [comment] 2020-06-07 13:50
Log rotation crash is fixed by: https://github.com/KomodoPlatform/atomicDEX-Pro/pull/223
If there will be another reproducable crash pleaase open separate issue

**Closed by tonymorony** 2020-06-07 13:50 UTC
Labels: P0, bug
