### ISSUE TITLE
error swapping max balance

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Pro#96] opened 2020-04-12 13:55 UTC
```
12 13:47:02, rpc:307] RPC error response: rpc:276] lp_ordermatch:697] utxo:1443] BCH balance 0.00837406 is too low, required 0.00846328
```
```
12 13:51:14, rpc:307] RPC error response: rpc:276] lp_ordermatch:697] utxo:1443] LTC balance 0.0098383 is too low, required 0.00992564
```
If i try to swap the entire balance (BCH/LTC) to KMD, mm2 shows the above errors and the order is not created.

btw, BCH fee is always `{"result":{"amount":"0.00001","coin":"BCH"}}`, it is fixed.

**Comment by Milerius** [comment] 2020-04-14 08:41
Is it happening on the 0.1.2 version @cipig ?

**Comment by cipig** [comment] 2020-04-14 08:54
yes, i compiled from dev branch

**Comment by Milerius** [comment] 2020-04-14 10:37
We are investigating, normally it's was solved by https://github.com/KomodoPlatform/atomicDEX-Pro/pull/78

**Comment by cipig** [comment] 2020-04-14 11:01
BCH txfee is fixed https://github.com/KomodoPlatform/coins/blob/master/coins#L218, so https://developers.atomicdex.io/basic-docs/atomicdex/atomicdex-api.html#get-trade-fee always returns the same value
txfee can only change for coins with txfee set to 0, like LTC https://github.com/KomodoPlatform/coins/blob/master/coins#L1741

**Comment by naezith** [comment] 2020-04-15 15:21
@cipig Are you aware that a similar swap doesn't work at mobile too?

By the way, (Google Play version 0.2.13) mobile fee is `0.0002` while PC one is `0.00002`. Keep that in mind at this example I'm giving.

I flushed my whole MORTY balance, leaving only `0.016`. 
At trade page I clicked MAX, then chose RICKY and the `0.5` price at Orderbook.
Trade fails, saying: `Not enough balance for fees - trade a smaller amount`

In this case, it might be a bug at `mm2`?

Math:
`0.01577941 + 0.0002 + 0.00002031 = 0.01599972` and I have `0.016`.

![image](https://user-images.githubusercontent.com/6732486/79354573-3e205a00-7f45-11ea-8ea5-34606c139798.png)

![image](https://user-images.githubusercontent.com/6732486/79354587-437da480-7f45-11ea-99ed-e6e2d5a7d4b6.png)

**Comment by cipig** [comment] 2020-04-15 16:54
can confirm this... did the same test on Android, with exact same result
from the logs:
```
2020-04-15 18:42:13.272880 api_providers:68] api postBuy {"error":"rpc:273] lp_ordermatch:678] utxo:1434] MORTY balance 0.016 is too low, required 0.01607942"}
2020-04-15 18:42:13.275596 swap_confirmation_page:406] MORTY balance 0.016 is too low, required 0.01607942
2020-04-15 18:42:13.275779 swap_confirmation_page:409]  0.01607942
2020-04-15 18:42:13.808189 market_maker_service:292] 15 16:42:13, rpc:304] RPC error response: rpc:273] lp_ordermatch:678] utxo:1434] MORTY balance 0.016 is too low, required 0.01607942
```

**Comment by ArtemGr** [comment] 2020-04-15 17:27
Have you looked at https://github.com/KomodoPlatform/atomicDEX-API/blob/7d10c66c033ae4e6cfccaea318e2bddc3db7ea35/mm2src/coins/utxo.rs#L1423 ?

**Comment by artemii235** [comment] 2020-04-16 04:42
The problem is dex fee has minimum threshold of `0.0001` to avoid dust issues with small trading amounts: https://github.com/KomodoPlatform/atomicDEX-API/blob/7d10c66c033ae4e6cfccaea318e2bddc3db7ea35/mm2src/lp_swap.rs#L329. 
`0.01577942 + 0.0002 + 0.0001 = 0.01607942` which equal to MM2 required amount.

**Comment by artemii235** [comment] 2020-04-16 04:47
@naezith @ArtemGr Please also pay attention to exchange rate displayed in mobile app, if you select `0.5` order the reverse pair exchange rate should be `2` exactly, not `1.99999873`. It is either initial order has slightly different price or there's some calculation error in AtomicDEX mobile GUI.

**Comment by naezith** [comment] 2020-04-16 09:53
> @naezith @ArtemGr Please also pay attention to exchange rate displayed in mobile app, if you select `0.5` order the reverse pair exchange rate should be `2` exactly, not `1.99999873`. It is either initial order has slightly different price or there's some calculation error in AtomicDEX mobile GUI.

At Desktop, it says `0.5` so it's fine for us.

**Comment by cipig** [comment] 2020-06-19 01:42
```
QMap(("input_final_value", QVariant(QString, "0.07164596"))("is_ticker_of_fees_eth", QVariant(bool, false))("trade_fee", QVariant(QString, "0.00009235"))("tx_fee", QVariant(QString, "0.00002000")))
[01:35:08 +00:00] [D] [thr 9877] get_trade_infos l873 f[atomic.dex.app.cpp]
qml: Getting Trade info with parameters:  DEX KMD 0.07175831  -  Result:  {"input_final_value":"0.07164596","is_ticker_of_fees_eth":false,"trade_fee":"0.00009235","tx_fee":"0.00002000"}
[01:35:08 +00:00] [D] [thr 9877] get_trade_infos l873 f[atomic.dex.app.cpp]
QMap(("input_final_value", QVariant(QString, "0.07175831"))("is_ticker_of_fees_eth", QVariant(bool, false))("trade_fee", QVariant(QString, "0.00009250"))("tx_fee", QVariant(QString, "0.00002000")))
qml: Getting Trade info with parameters:  DEX KMD 0.07187081  -  Result:  {"input_final_value":"0.07175831","is_ticker_of_fees_eth":false,"trade_fee":"0.00009250","tx_fee":"0.00002000"}
[01:35:09 +00:00] [D] [thr 9877] get_trade_infos l873 f[atomic.dex.app.cpp]
QMap(("input_final_value", QVariant(QString, "0.07164596"))("is_ticker_of_fees_eth", QVariant(bool, false))("trade_fee", QVariant(QString, "0.00009235"))("tx_fee", QVariant(QString, "0.00002000")))
qml: Getting Trade info with parameters:  DEX KMD 0.07175831  -  Result:  {"input_final_value":"0.07164596","is_ticker_of_fees_eth":false,"trade_fee":"0.00009235","tx_fee":"0.00002000"}
[01:35:09 +00:00] [D] [thr 9877] get_trade_infos l873 f[atomic.dex.app.cpp]
QMap(("input_final_value", QVariant(QString, "0.07175831"))("is_ticker_of_fees_eth", QVariant(bool, false))("trade_fee", QVariant(QString, "0.00009250"))("tx_fee", QVariant(QString, "0.00002000")))
qml: Getting Trade info with parameters:  DEX KMD 0.07187081  -  Result:  {"input_final_value":"0.07175831","is_ticker_of_fees_eth":false,"trade_fee":"0.00009250","tx_fee":"0.00002000"}
qml: QML place_sell_order: max balance: 0.07187081
qml: QML place_sell_order: params: DEX  <->  KMD   /  price: 10.49999947500002624999868750006562499671875016406249179687541015622949218852539057373047131347643433   /  volume: 0.07175831
qml: QML place_sell_order: trade info: {"input_final_value":"0.07164596","is_ticker_of_fees_eth":false,"trade_fee":"0.00009235","tx_fee":"0.00002000"}
 base:  "DEX"  rel:  "KMD"  price:  "10.49999947500002624999868750006562499671875016406249179687541015622949218852539057373047131347643433"  volume:  "0.07175831"
[01:35:09 +00:00] [D] [thr 9877] place_sell_order l989 f[atomic.dex.mm2.cpp]
[01:35:09 +00:00] [I] [thr 9877] Processing rpc call: sell
[01:35:09 +00:00] [D] [thr 9877] request: {"base":"DEX","method":"sell","price":"10.49999947500002624999868750006562499671875016406249179687541015622949218852539057373047131347643433","rel":"KMD","userpass":"*******","volume":"0.07175831"}
19 01:35:09, rpc:334] RPC error response: rpc:303] lp_ordermatch:742] utxo:1498] DEX balance 0.07187081 is too low, required 0.07187831
[01:35:09 +00:00] [I] [thr 9877] resp code for rpc_command sell is 500
[01:35:09 +00:00] [W] [thr 9877] rpc answer code is not 200, body : {"error":"rpc:303] lp_ordermatch:742] utxo:1498] DEX balance 0.07187081 is too low, required 0.07187831"}
```
is shown in console on latest dev when this happens... maybe it helps

**Comment by Milerius** [comment] 2020-06-19 08:29
```
0.07164596 + 0.00009235 + 0.00002000

0.07175831
```

Your max balance is `0.07187081` which is > `0.07175831`

The call of `request: {"base":"DEX","method":"sell","price":"10.49999947500002624999868750006562499671875016406249179687541015622949218852539057373047131347643433","rel":"KMD","userpass":"*******","volume":"0.07175831"}`

is well formed (still under the max balance).

If you want to swap your max balance here: `0.07187081`

You maximum is: `0.07175846` which is `0.07187081 - (0.00009235 + 0.00002000)`

which is btw > `0.07175831`

Why mm2 refuse this input ?

**Comment by artemii235** [comment] 2020-06-19 09:03
MM2 refuses the input because it has `0.0001` minimal dex fee threshold: https://github.com/KomodoPlatform/atomicDEX-Pro/issues/96#issuecomment-614412181. So dex fee is `0.0001` and not `0.00009235`. Total required amount is `0.07175831 + 0.0001 + 0.00002 = 0.07187831` and `0.07187831` is returned as required from MM2 which is expected behavior actually.

I have recently added `max_taker_vol` RPC method that is not documented yet (https://github.com/KomodoPlatform/atomicDEX-API/pull/671#issuecomment-641923083), it will be best to switch to it for every GUI some day because there might be some implementation details in dex fee and other stuff calculation that will be hard to port and support in every application using MM2.

**Comment by tonymorony** [comment] 2020-06-21 18:43
Thanks! That metod looks very promising :) We'll try to add `max_taker_vol` into 0.1.5 right after this one fix: https://github.com/KomodoPlatform/atomicDEX-API/issues/684

**Comment by tonymorony** [comment] 2020-07-03 07:31
https://github.com/KomodoPlatform/atomicDEX-Pro/pull/286 was merged, now we have to connect frontend MAX button to it @Milerius @naezith

**Closed** 2020-08-18 17:26 UTC
Labels: 0.2.0, P1, bug, full-stack
